### ISSUE TITLE
[1.3] Update DALI

### ISSUE THREAD

**Issue by jayfurmanek** [open-ce/DALI-feedstock#23]
DALI did hit 1.0 and is continuing on with subsequent releases

https://github.com/NVIDIA/DALI/releases

Update DALI for Open-CE 1.3 with a version that will match with TF 2.5.

**Comment by JanuszL** [comment]
@jayfurmanek,

Do you think we can unify https://github.com/NVIDIA/DALI/blob/master/conda/recipe/build.sh and https://github.com/open-ce/DALI-feedstock/blob/main/recipe/build.sh?
If you need any help let us know.

**Comment by jayfurmanek** [comment]
@JanuszL I think that's a good idea. Our recipe definitely needs an update, it would be good to have it close to the official one.
I'll keep you in the loop as needed when we get to this, which should be this month.

**Comment by cdeepali** [comment]
The following recipes also need to be refreshed:

- [x] libsndfile-feedstock
- [x] libflac-feedstock
- [x] opencv-feedstock
- [x] jpeg-turbo-feedstock/
